# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a3a8d6e05c0d3fe268172dc11aa5bb203931e84833ad888488d0ef332a35dd8bd5f107c66f6b59a89b467fec79f470ba0aaf7410f2765cc67e7b3fd48364b0c3

test:
  secret_key_base: ad4db97dfa185a4b8ec8b0b3af476766b796a8dbaf0e05fa2a546f069bb6ce72f5bc80d849680261d6ada39864c2d5fdff19cd08fb52689093449236affc13e8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
